name: 'Create GitHub Release'
description: 'Create a GitHub release with a changelog'
inputs:
  tag:
    description: 'Tag to use for the release'
    required: true
  target:
    description: 'Which commit or branch to point the release tag to'
    required: true
  changelog:
    description: 'Text to use for the release body'
    required: true
  github-token:
    description: 'GitHub Token'
    required: true
  prerelease:
    description: "Release should be marked as a prerelease"
    required: false
  draft:
    description: "Release should be marked as a draft"
    required: false
  files:
    description: "Newline-delimited globs of paths to assets to upload for release"
    required: false
runs:
  using: "composite"
  steps:
    - name: Add prefix
      id: tag-prefixed
      shell: bash
      run: |
        if [[ ! "$TAG" =~ ^v.* ]]; then
          echo "tag=v$TAG" >> "$GITHUB_OUTPUT"
        else
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        fi
      env:
        TAG: ${{ inputs.tag }}
    - name: Create Release
      id: create-release
      uses: softprops/action-gh-release@v2.0.4
      with:
        tag_name: ${{ steps.tag-prefixed.outputs.tag }}
        body: ${{ inputs.changelog }}
        prerelease: ${{ inputs.prerelease }}
        draft: ${{ inputs.draft }}
        target_commitish: ${{ inputs.target }}
        files: ${{ inputs.files }}
        fail_on_unmatched_files: true
outputs:
  release-id:
    description: 'ID of the created release'
    value: ${{ steps.create-release.outputs.id }}
  release-url:
    description: 'URL of the release'
    value: ${{ steps.create-release.outputs.url }}
  release-upload-url:
    description: 'URL for uploading assets to the release'
    value: ${{ steps.create-release.outputs.upload_url }}