name: 'Create GitHub Release'
description: 'Create a GitHub release with a changelog'
inputs:
  tag:
    description: 'Tag to use for the release'
    required: true
  target:
    description: 'Which commit or branch to point the release tag to'
    required: true
  changelog:
    description: 'Text to use for the release body'
    required: true
  github-token:
    description: 'GitHub Token'
    required: true
  prerelease:
    description: "Release should be marked as a prerelease"
    required: false
  draft:
    description: "Release should be marked as a draft"
    required: false
runs:
  using: "composite"
  steps:
    - name: Create Release
      id: create-release
      uses: mikepenz/action-gh-release@v0.2.0-a03
      with:
        tag_name: ${{ inputs.tag }}
        body: ${{steps.changelog.outputs.changelog}}
        prerelease: ${{ inputs.prerelease }}
        draft: ${{ inputs.draft }}
        target_commitish: ${{ inputs.target }}
outputs:
  release-id:
    description: 'ID of the created release'
    value: ${{ steps.create-release.outputs.id }}
  release-url:
    description: 'URL of the release'
    value: ${{ steps.create-release.outputs.url }}
  release-upload-url:
    description: 'URL for uploading assets to the release'
    value: ${{ steps.create-release.outputs.upload_url }}