name: 'Release Notes - GH'
description: 'Build the GitHub Release notes'
inputs:
  tag:
    description: 'Tag to use for the release'
    required: false
  github-token:
    description: 'GitHub Token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: Build Changelog
      id: github_release
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Create Release
      uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
      with:
        body: ${{steps.github_release.outputs.changelog}}
