name: 'Semantic PR'
description: "Require all PR's have a semantic versioning title."

inputs:
  github-token:
    description: 'GitHub Token'
    required: true

runs:
  using: "composite"
  steps:
    - uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}