name: 'Release Notes - GH'
description: 'Build the GitHub Release notes'
inputs:
  tag:
    description: 'Tag to use for the release'
    required: false
  github-token:
    description: 'GitHub Token'
    required: true
  prerelease:
    description: "Release should be marked as a prerelease"
    required: false
  draft:
    description: "Release should be marked as a draft"
    required: false

outputs:
  latest-tag:
    description: 'Latest tag prior to running this action'
    value: ${{ steps.latestrelease.outputs.tag_name }}
  release-tag:
    description: 'Tag used for the release'
    value: ${{ steps.semverbump.outputs.v_minor }}
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get latest non-prerelease release
      id: latestrelease
      uses: cardinalby/git-get-release-action@v1
      with:
        latest: true
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Get next minor version
      id: semverbump
      uses: WyriHaximus/github-action-next-semvers@v1.2.1
      with:
        version: ${{ steps.latestrelease.outputs.tag_name }}
    - name: Build Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v3
      with:
        ignorePreReleases: true
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Create Release
      uses: mikepenz/action-gh-release@v0.2.0-a03
      with:
        tag_name: ${{ inputs.prerelease == "true" && format('{0}-{1}{2}', steps.semverbump.outputs.v_minor, 'prerelease', github.run_id) || steps.semverbump.outputs.v_minor }}
        body: ${{steps.changelog.outputs.changelog}}
        prerelease: ${{ inputs.prerelease }}
        draft: ${{ inputs.draft }}
