name: 'Release Notes - GH'
description: 'Build the GitHub Release notes'
inputs:
  tag:
    description: 'Tag to use for the release'
    required: false
  github-token:
    description: 'GitHub Token'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Get Previous semver tag
      id: previoustag
      uses: WyriHaximus/github-action-get-previous-tag@v1.3.0
      with:
        prefix: v
    - name: Get next minor version
      id: semverbump
      uses: WyriHaximus/github-action-next-semvers@v1.2.1
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - name: Build Changelog
      id: changelog
      uses: mikepenz/release-changelog-builder-action@v3
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
    - name: Create Release
      uses: mikepenz/action-gh-release@v0.2.0-a03 #softprops/action-gh-release
      with:
        tag_name: ${{ steps.semverbump.outputs.v_minor }}
        body: ${{steps.changelog.outputs.changelog}}
