name: 'Release Notes - GH'
description: 'Build the GitHub Release notes'
inputs:
  tag:
    description: 'Tag to use for the release'
    required: false
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3
    - name: 'Get Previous tag'
      id: previoustag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0 # Optional fallback tag to use when no tag can be found
    - name: 'Get next minor version'
      id: semvers
      uses: "WyriHaximus/github-action-next-semvers@v1"
      with:
        version: ${{ steps.previoustag.outputs.tag }}
    - name: "Build Changelog"
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v4
    - uses: ncipollo/release-action@v1.12
      with:
        artifacts: "release.tar.gz,foo/*.txt"
        body: ${{steps.build_changelog.outputs.changelog}}
        allowUpdates: true
        commit: main
        tag: ${{ steps.semvers.outputs.patch }}
