on:
  workflow_dispatch:
name: Test Custom Release Action
jobs:
 test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}